// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOngqdjT-eWUvreCiK9MlDSQ1cDd2l974',
    appId: '1:326324387146:web:b2bf30600eb70e1c9755b3',
    messagingSenderId: '326324387146',
    projectId: 'fir-hostingwebtest',
    authDomain: 'fir-hostingwebtest.firebaseapp.com',
    storageBucket: 'fir-hostingwebtest.appspot.com',
    measurementId: 'G-C065EXZBQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFq1JoKZwGdqFXO6O6qoKcxSZtoqGuH5c',
    appId: '1:326324387146:android:4a708b4093ee65fd9755b3',
    messagingSenderId: '326324387146',
    projectId: 'fir-hostingwebtest',
    storageBucket: 'fir-hostingwebtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCssmD2UZC95i2XiqoXGRn-BNTHz5g5t7k',
    appId: '1:326324387146:ios:4ad66270e7ea7eac9755b3',
    messagingSenderId: '326324387146',
    projectId: 'fir-hostingwebtest',
    storageBucket: 'fir-hostingwebtest.appspot.com',
    iosBundleId: 'com.example.firebasehosting',
  );
}
